import type { ErdColumn, ErdModel, ErdRelationship, ErdTable } from '../types/erd';

function quoteIdentifier(name: string): string {
  return `[${name.replace(/\]/g, ']]')}]`;
}

function sanitizeConstraintName(name: string): string {
  return name.replace(/[^A-Za-z0-9_]+/g, '_');
}

function getPrimaryKeyColumns(table: ErdTable): ErdColumn[] {
  const primaryKeys = table.columns.filter((column) => column.isPrimaryKey);
  if (primaryKeys.length > 0) return primaryKeys;
  return table.columns.slice(0, 1);
}

function sqlTypeForColumn(column: ErdColumn): string {
  const type = column.type || 'string';
  const normalized = type.replace(/\?$/, '');

  if (column.isPrimaryKey && normalized === 'string') return 'NVARCHAR(450)';
  if (normalized === 'string') return 'NVARCHAR(MAX)';
  if (normalized === 'int') return 'INT';
  if (normalized === 'long') return 'BIGINT';
  if (normalized === 'short') return 'SMALLINT';
  if (normalized === 'decimal') return 'DECIMAL(18, 2)';
  if (normalized === 'double') return 'FLOAT';
  if (normalized === 'float') return 'REAL';
  if (normalized === 'bool') return 'BIT';
  if (normalized === 'DateTime') return 'DATETIME2';
  if (normalized === 'DateTimeOffset') return 'DATETIMEOFFSET';
  if (normalized === 'Guid') return 'UNIQUEIDENTIFIER';
  if (normalized === 'byte[]') return 'VARBINARY(MAX)';
  if (normalized === 'char') return 'NCHAR(1)';
  return 'NVARCHAR(MAX)';
}

function isIdentityEligibleType(column: ErdColumn): boolean {
  return ['int', 'long', 'short'].includes((column.type || 'string').replace(/\?$/, ''));
}

function defaultClauseForColumn(column: ErdColumn): string {
  if (column.defaultGeneration !== 'current-timestamp') return '';
  return (column.type || 'DateTime').replace(/\?$/, '') === 'DateTimeOffset'
    ? 'DEFAULT SYSDATETIMEOFFSET()'
    : 'DEFAULT CURRENT_TIMESTAMP';
}

function columnDefinition(column: ErdColumn): string {
  const isNullable = column.isPrimaryKey ? false : column.isNullable;
  const identityClause = column.isPrimaryKey && isIdentityEligibleType(column) ? ' IDENTITY(1, 1)' : '';
  const defaultClause = defaultClauseForColumn(column);
  return `    ${quoteIdentifier(column.name)} ${sqlTypeForColumn(column)}${identityClause} ${isNullable ? 'NULL' : 'NOT NULL'}${defaultClause ? ` ${defaultClause}` : ''}`;
}

function primaryKeyDefinition(table: ErdTable): string | null {
  const primaryKeys = getPrimaryKeyColumns(table);
  if (primaryKeys.length === 0) return null;
  return `    CONSTRAINT ${quoteIdentifier(sanitizeConstraintName(`PK_${table.name}`))} PRIMARY KEY (${primaryKeys.map((column) => quoteIdentifier(column.name)).join(', ')})`;
}

function foreignKeyDefinition(model: ErdModel, relationship: ErdRelationship): string | null {
  const dependentTable = model.tables.find((table) => table.id === relationship.dependentTable);
  const principalTable = model.tables.find((table) => table.id === relationship.principalTable);
  if (!dependentTable || !principalTable) return null;

  const dependentColumns = relationship.foreignKeyColumns;
  const principalColumns = getPrimaryKeyColumns(principalTable).map((column) => column.name);
  const referencedColumns = principalColumns.length === dependentColumns.length ? principalColumns : principalColumns.slice(0, dependentColumns.length);
  if (referencedColumns.length === 0 || referencedColumns.length !== dependentColumns.length) return null;

  const constraintName = sanitizeConstraintName(`FK_${dependentTable.name}_${principalTable.name}_${dependentColumns.join('_')}`);

  return [
    `ALTER TABLE ${quoteIdentifier('dbo')}.${quoteIdentifier(dependentTable.name)}`,
    `ADD CONSTRAINT ${quoteIdentifier(constraintName)}`,
    `FOREIGN KEY (${dependentColumns.map((column) => quoteIdentifier(column)).join(', ')})`,
    `REFERENCES ${quoteIdentifier('dbo')}.${quoteIdentifier(principalTable.name)} (${referencedColumns.map((column) => quoteIdentifier(column)).join(', ')})`,
    'ON DELETE CASCADE;',
  ].join('\n');
}

export function generateErdSql(model: ErdModel): string {
  const lines: string[] = [
    '-- Generated by Schema Sculptor',
    '-- Cascade delete is assumed for all relationships.',
    '',
  ];

  if (model.tables.length === 0) {
    lines.push('-- No tables to export.');
    return lines.join('\n');
  }

  for (const table of model.tables) {
    const columnLines = table.columns.map(columnDefinition);
    const primaryKeyLine = primaryKeyDefinition(table);
    if (primaryKeyLine) columnLines.push(primaryKeyLine);
    lines.push(`CREATE TABLE ${quoteIdentifier('dbo')}.${quoteIdentifier(table.name)} (`);
    lines.push(columnLines.join(',\n'));
    lines.push(');');
    lines.push('GO', '');
  }

  for (const relationship of model.relationships) {
    const foreignKey = foreignKeyDefinition(model, relationship);
    if (!foreignKey) continue;
    lines.push(foreignKey);
    lines.push('GO', '');
  }

  return lines.join('\n');
}